const detail = (section, slug, type, title, order) => ({ route: `/${section}/${slug}/`, slug, type, title, seoTitle: `${title} | Easylink`, seoDescription: `${title} Easylink tartalom.`, heroEyebrow: section === 'megoldasaink' ? 'Megoldásaink' : 'Kinek szól?', heroTitle: title, heroDescription: `${title} áttekintés és szerkeszthető public tartalom.`, heroAsset: '/assets/nati/hero-bg-flow-01.webp', status: 'published', sortOrder: order, blocks: [{ type: 'text', title: 'Mire jó?', body: `${title} rövid szerkeszthető összefoglalója.` }, { type: 'feature-list', title: 'Konkrét fókuszok', items: ['Átlátható működés', 'Kevesebb manuális adminisztráció', 'Vezetői kontrollpontok'] }] });
export const staticPagesData = [
  { route: '/', slug: 'home', type: 'home', title: 'Easylink', seoTitle: 'Easylink | Ügyviteli rendszer KKV-knak', seoDescription: 'Modern Easylink public site ügyviteli, integrációs és AI asszisztens iránnyal.', heroEyebrow: 'Easylink public site', heroTitle: 'Ügyviteli rendszer, amely összeköti a napi működésed.', heroDescription: 'Pénzügy, CRM, dokumentumok, kontrolling és AI asszisztens irány egy vezetői felületen.', heroAsset: '/assets/nati/hero-bg-flow-03.webp', status: 'published', sortOrder: 0, blocks: [{ type: 'text', title: 'Public site előkészítés', body: 'Nem még egy táblázat, hanem egy átlátható vezetői felület.' }, { type: 'feature-list', title: 'Megoldásaink', items: ['Pénzügy és számlázás', 'HR és Munkaügy', 'CRM és ügyfélkezelés'] }] },
  { route: '/megoldasaink/', slug: 'megoldasaink', type: 'solutions_index', title: 'Megoldásaink', seoTitle: 'Megoldásaink | Easylink', seoDescription: 'Easylink ügyviteli megoldások.', heroEyebrow: 'Megoldásaink', heroTitle: 'Egy rendszer a napi működés kulcspontjaira.', heroDescription: 'Moduláris ügyviteli irányok pénzügyre, CRM-re, dokumentumokra, kontrollingra és AI-ra.', heroAsset: '/assets/nati/hero-bg-flow-01.webp', status: 'published', sortOrder: 10, blocks: [{ type: 'feature-list', title: 'Megoldás lista', items: ['penzugy-szamlazas', 'hr-munkaugy', 'crm-ugyfelkezeles', 'dokumentumkezeles-adminisztracio', 'kontrolling', 'ai-asszisztens'] }] },
  detail('megoldasaink', 'penzugy-szamlazas', 'solution_detail', 'Pénzügy és számlázás', 11),
  detail('megoldasaink', 'hr-munkaugy', 'solution_detail', 'HR és Munkaügy', 12),
  detail('megoldasaink', 'crm-ugyfelkezeles', 'solution_detail', 'CRM és ügyfélkezelés', 13),
  detail('megoldasaink', 'dokumentumkezeles-adminisztracio', 'solution_detail', 'Dokumentumkezelés és adminisztráció', 14),
  detail('megoldasaink', 'kontrolling', 'solution_detail', 'Kontrolling', 15),
  detail('megoldasaink', 'ai-asszisztens', 'solution_detail', 'EasyLink AI Asszisztens', 16),
  { route: '/kinek-szol/', slug: 'kinek-szol', type: 'audiences_index', title: 'Kinek szól?', seoTitle: 'Kinek szól? | Easylink', seoDescription: 'Easylink célcsoportok.', heroEyebrow: 'Kinek szól?', heroTitle: 'Hoteleknek, vendéglátóhelyeknek és szolgáltató vállalkozásoknak.', heroDescription: 'Iparági fókuszú ügyviteli struktúrák.', heroAsset: '/assets/nati/hero-bg-flow-02.webp', status: 'published', sortOrder: 20, blocks: [{ type: 'audience_list', title: 'Célcsoportok', items: ['hotelek-szallashelyek', 'vendeglatohelyek', 'szolgaltato-vallalkozasok'] }] },
  detail('kinek-szol', 'hotelek-szallashelyek', 'audience_detail', 'Hoteleknek és szálláshelyeknek', 21),
  detail('kinek-szol', 'vendeglatohelyek', 'audience_detail', 'Vendéglátóhelyeknek', 22),
  detail('kinek-szol', 'szolgaltato-vallalkozasok', 'audience_detail', 'Szolgáltató vállalkozásoknak', 23),
  { route: '/integraciok/', slug: 'integraciok', type: 'integrations', title: 'Integrációk', seoTitle: 'Integrációk | Easylink', seoDescription: 'Integrációs irányok és adatkapcsolatok.', heroEyebrow: 'Integrációk', heroTitle: 'Kapcsolódások, adatáramlás, tisztább működés.', heroDescription: 'Az Easylink célja, hogy a fontos üzleti adatok összekapcsolhatók legyenek.', heroAsset: '/assets/nati/hero-bg-flow-01.webp', status: 'published', sortOrder: 30, blocks: [{ type: 'integration_list', title: 'Integrációs irányok', items: ['NAV Online Számla', 'Magyar bankok / PSD2 / Aggreg8', 'Hostware', 'Számlázz.hu', 'Billingo', 'Cégjelző'] }] },
  { route: '/arak/', slug: 'arak', type: 'pricing', title: 'Árak', seoTitle: 'Árak | Easylink', seoDescription: 'Easylink árazási irányok.', heroEyebrow: 'Árak', heroTitle: 'Árazás a bevezetési scope alapján.', heroDescription: 'Az Easylink bevezetés modulokra, integrációs igényre és ügyviteli folyamatokra szabható.', heroAsset: '/assets/nati/hero-bg-flow-02.webp', status: 'published', sortOrder: 40, blocks: [{ type: 'text', title: 'Egyedi ajánlat', body: 'A pontos ár a kiválasztott moduloktól és integrációs előfeltételektől függ.' }] },
  { route: '/kapcsolat/', slug: 'kapcsolat', type: 'contact', title: 'Kapcsolat', seoTitle: 'Kapcsolat | Easylink', seoDescription: 'Kapcsolatfelvétel Easylink bevezetéshez.', heroEyebrow: 'Kapcsolat', heroTitle: 'Beszéljük át, mire van szükséged.', heroDescription: 'Kérj bemutatót vagy egyeztetést az Easylink bevezetési lehetőségeiről.', heroAsset: '/assets/nati/hero-bg-flow-03.webp', status: 'published', sortOrder: 50, blocks: [{ type: 'text', title: 'Kapcsolatfelvétel', body: 'A deploy/ügyfél felület és a site admin felhasználókezelése külön marad.' }] },
];
export const staticNavigationData = [
  { title: 'Megoldásaink', href: '/megoldasaink/', sortOrder: 1, status: 'published' },
  { title: 'Kinek szól?', href: '/kinek-szol/', sortOrder: 2, status: 'published' },
  { title: 'Integrációk', href: '/integraciok/', sortOrder: 3, status: 'published' },
  { title: 'Áraink', href: '/arak/', sortOrder: 4, status: 'published' },
  { title: 'Kapcsolat', href: '/kapcsolat/', sortOrder: 5, status: 'published' },
];
