import { esc } from './utils.mjs';

export function settingsSaveOutcome(j) {
  if (!j?.ok) return { ok: false, message: j?.error?.message || 'Mentési hiba.' };
  if (j.publish?.ok) return { ok: true, message: 'Beállítások mentve és élesítve.' };
  if (j.publish?.status === 'publish_in_progress') return { ok: false, message: 'Beállítások mentve, de az élesítés folyamatban van; az élő oldal változatlan.' };
  return { ok: false, message: 'Beállítások mentve, de az élesítés sikertelen; az élő oldal változatlan maradt.' };
}

export function settingsAdminJs() {
  return `const settingsSaveOutcome=${settingsSaveOutcome.toString()};const msg=(t,ok=true)=>{document.getElementById('msg').innerHTML='<p class="msg '+(ok?'ok':'err')+'">'+String(t).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))+'</p>';};function payload(){const f=document.getElementById('settings-form');return {analytics:{enabled:f.elements['analytics.enabled'].checked,provider:f.elements['analytics.provider'].value,ga4MeasurementId:f.elements['analytics.ga4MeasurementId'].value,consentMode:f.elements['analytics.consentMode'].value,consentConfigurationVersion:Number(f.elements['analytics.consentConfigurationVersion'].value)},legalDocuments:{termsPdfPath:f.elements['legalDocuments.termsPdfPath'].value,privacyPdfPath:f.elements['legalDocuments.privacyPdfPath'].value,cookiePdfPath:f.elements['legalDocuments.cookiePdfPath'].value}};}async function save(){const r=await fetch('/api/admin/settings',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(payload())});const j=await r.json();const outcome=settingsSaveOutcome(j);msg(outcome.message,outcome.ok);if(outcome.ok)location.reload();return j;}document.getElementById('settings-form').onsubmit=async e=>{e.preventDefault();await save();};document.querySelectorAll('[data-clear-doc]').forEach(b=>b.onclick=async()=>{document.querySelector('[name="legalDocuments.'+b.dataset.clearDoc+'"]').value='';await save();});document.querySelectorAll('[data-doc-upload]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();const fd=new FormData(f);const r=await fetch('/api/admin/media',{method:'POST',body:fd});const j=await r.json();if(!j.ok){msg(j.error?.message||'Feltöltési hiba',false);return;}document.querySelector('[name="legalDocuments.'+f.dataset.docUpload+'"]').value=j.data.path;await save();});`;
}

export function settingsPanel(settings) {
  const l = settings.legalDocuments || {};
  const a = settings.analytics || {};
  const doc = (key, title, path) => `<section class="card" data-legal-section="${key}"><h3>${title}</h3><p>Aktuális dokumentum: ${path ? `<a href="${esc(path)}" target="_blank" rel="noopener noreferrer">PDF megnyitása</a><br><code>${esc(path)}</code>` : 'nincs beállítva'}</p><form data-doc-upload="${key}"><input type="file" name="file" accept="application/pdf" required><input type="hidden" name="alt" value="${title}"><button type="submit">Új PDF feltöltése és hozzárendelése</button></form><button type="button" class="secondary" data-clear-doc="${key}">Hozzárendelés eltávolítása</button></section>`;
  return `<div id="msg"></div><h2>Alapadatok</h2><form class="card" id="settings-form"><h3>Analytics konfiguráció</h3><label><input type="checkbox" name="analytics.enabled" ${a.enabled ? 'checked' : ''}> Analytics engedélyezve</label><label>Szolgáltató<select name="analytics.provider"><option value="none" ${a.provider === 'none' ? 'selected' : ''}>none</option><option value="ga4" ${a.provider === 'ga4' ? 'selected' : ''}>ga4</option></select></label><label>GA4 Measurement ID<input name="analytics.ga4MeasurementId" value="${esc(a.ga4MeasurementId || '')}" placeholder="G-XXXXXXXX"></label><label>Consent mode<select name="analytics.consentMode"><option value="basic" selected>basic</option></select></label><label>Consent konfiguráció verzió<input name="analytics.consentConfigurationVersion" type="number" min="1" step="1" value="${esc(a.consentConfigurationVersion || 1)}"></label><input type="hidden" name="legalDocuments.termsPdfPath" value="${esc(l.termsPdfPath || '')}"><input type="hidden" name="legalDocuments.privacyPdfPath" value="${esc(l.privacyPdfPath || '')}"><input type="hidden" name="legalDocuments.cookiePdfPath" value="${esc(l.cookiePdfPath || '')}"><button type="submit">Beállítások mentése és élesítés</button></form>${doc('termsPdfPath', 'Általános Szerződési Feltételek', l.termsPdfPath)}${doc('privacyPdfPath', 'Adatkezelési Tájékoztató', l.privacyPdfPath)}${doc('cookiePdfPath', 'Cookie Tájékoztató', l.cookiePdfPath)}<script>${settingsAdminJs()}</script>`;
}
