import type { PublicContentItem } from './types';

export const solutions: PublicContentItem[] = [
  { title:'Pénzügy és számlázás', slug:'penzugy-szamlazas', shortDescription:'Számlák, pénzügyi státuszok és teendők áttekinthető vezetői felületen.', order:1, seoTitle:'Pénzügy és számlázás | Easylink', seoDescription:'Pénzügyi és számlázási folyamatok egy átlátható Easylink felületen.', heroTitle:'Pénzügy és számlázás', heroDescription:'Kövesd a számlázási folyamatokat, fizetési státuszokat és pénzügyi prioritásokat egy helyen.', blocks:[{type:'feature-list',title:'Mit támogat?',items:['Számlázási áttekintés és státuszkövetés','NAV Online Számla irány előkészítése','Vezetői pénzügyi prioritások']}], media:{path:'/assets/nati/solutions/penzugy-szamlazas.webp',alt:'Pénzügyi adatáramlás placeholder',todo:'Nati végleges pénzügyi vizuálja kerül ide.'}, status:'published' },
  { title:'HR és Munkaügy', slug:'hr-munkaugy', shortDescription:'Munkaügyi adminisztráció és csapatadatok későbbi egységes kezeléséhez.', order:2, seoTitle:'HR és Munkaügy | Easylink', seoDescription:'HR és munkaügyi adminisztráció Easylink struktúrában.', heroTitle:'HR és Munkaügy', heroDescription:'Készíts elő átlátható munkaügyi folyamatokat és kevesebb manuális adminisztrációt.', blocks:[{type:'feature-list',title:'Fókuszterületek',items:['Csapatadatok rendezett modellben','Munkaügyi dokumentumok előkészítése','Adminisztratív feladatok áttekintése']}], media:{path:'/assets/nati/solutions/hr-munkaugy.webp',alt:'HR adatkapcsolatok placeholder',todo:'Nati HR vizuálja kerül ide.'}, status:'published' },
  { title:'CRM és ügyfélkezelés', slug:'crm-ugyfelkezeles', shortDescription:'Ügyféladatok, kapcsolódó dokumentumok és következő lépések tiszta nézetben.', order:3, seoTitle:'CRM és ügyfélkezelés | Easylink', seoDescription:'CRM és ügyfélkezelés egy modern ügyviteli rendszerben.', heroTitle:'CRM és ügyfélkezelés', heroDescription:'Lásd egyben az ügyfeleket, előzményeket, feladatokat és döntési pontokat.', blocks:[{type:'feature-list',title:'Ügyfélkép',items:['Ügyféladatok és előzmények','Következő teendők','Dokumentumkapcsolatok']}], media:{path:'/assets/nati/solutions/crm-ugyfelkezeles.webp',alt:'CRM hálózat placeholder',todo:'Nati CRM vizuálja kerül ide.'}, status:'published' },
  { title:'Dokumentumkezelés és adminisztráció', slug:'dokumentumkezeles-adminisztracio', shortDescription:'Kevesebb manuális adminisztráció, rendezettebb dokumentumfolyamatok.', order:4, seoTitle:'Dokumentumkezelés és adminisztráció | Easylink', seoDescription:'Dokumentumkezelési és adminisztrációs Easylink megoldások.', heroTitle:'Dokumentumkezelés és adminisztráció', heroDescription:'Tedd átláthatóvá az adminisztrációt, dokumentumokat és jóváhagyási pontokat.', blocks:[{type:'feature-list',title:'Rendezett működés',items:['Dokumentumstátuszok','Admin teendők','Egységes kereshető struktúra']}], media:{path:'/assets/nati/solutions/dokumentumkezeles.webp',alt:'Dokumentum adatáramlás placeholder',todo:'Nati dokumentumkezelési vizuálja kerül ide.'}, status:'published' },
  { title:'Kontrolling', slug:'kontrolling', shortDescription:'Vezetői riportok, üzleti pulzus és kontrollpontok előkészítve.', order:5, seoTitle:'Kontrolling | Easylink', seoDescription:'Kontrolling és vezetői áttekintés Easylinkben.', heroTitle:'Kontrolling', heroDescription:'Kapj gyorsabb rálátást a működésre, kockázatokra és prioritásokra.', blocks:[{type:'feature-list',title:'Vezetői kontroll',items:['Üzleti pulzus','Kockázati jelzések','Riportstruktúra']}], media:{path:'/assets/nati/solutions/kontrolling.webp',alt:'Kontrolling dashboard placeholder',todo:'Nati kontrolling vizuálja kerül ide.'}, status:'published' },
  { title:'EasyLink AI Asszisztens', slug:'ai-asszisztens', shortDescription:'Kérdezz, és a rendszered válaszol az üzleti adataid alapján.', order:6, seoTitle:'EasyLink AI Asszisztens | Easylink', seoDescription:'AI asszisztens vezetői kérdésekhez és adatkapcsolatokhoz.', heroTitle:'Kérdezz, és a rendszered válaszol!', heroDescription:'Az EasyLink AI Asszisztens a számlázási, CRM és adminisztrációs adatokból segít gyors, érthető válaszokat adni.', blocks:[{type:'ai-preview',title:'EasyLink AI Asszisztens üzenet',body:'3 ügyfélnél magas a késedelmes fizetési kockázat. Javasolt következő lépés: automatikus emlékeztető és pénteki utánkövetés.'}], media:{path:'/assets/nati/solutions/ai-asszisztens.webp',alt:'AI adatáramlás placeholder',todo:'Nati futurisztikus AI/adatáramlás képe kerül ide.'}, status:'published' }
];

export const publishedSolutions = solutions.filter((item) => item.status === 'published').sort((a,b)=>a.order-b.order);
