export const LEGACY_LOGO_PATH = '/assets/brand/easylink-logo-horizontal.png';
export const DEFAULT_DEPLOY_URL = process.env.PUBLIC_DEPLOY_URL || 'https://deploy.easylink.hu';
export const SOCIAL_PLATFORMS = ['facebook','instagram','tiktok','youtube','linkedin'];
export const LEGAL_DOCUMENT_TYPES = ['terms','privacy','cookie'];
export const DEFAULT_LEGAL_DOCUMENT_ITEMS = [
  { type: 'terms', label: 'Általános Szerződési Feltételek', pdfPath: '', active: true, order: 1 },
  { type: 'privacy', label: 'Adatkezelési Tájékoztató', pdfPath: '', active: true, order: 2 },
  { type: 'cookie', label: 'Cookie Tájékoztató', pdfPath: '', active: true, order: 3 },
];
export const DEFAULT_SITE_SETTINGS = {
  analytics: { enabled: false, provider: 'none', ga4MeasurementId: '', consentMode: 'basic', consentConfigurationVersion: 1 },
  legalDocuments: { termsPdfPath: '', privacyPdfPath: '', cookiePdfPath: '', items: DEFAULT_LEGAL_DOCUMENT_ITEMS },
  contact: { companyName: '', email: 'hello@easylink.hu', phone: '', postalCode: '', city: '', addressLine: '', country: 'Magyarország' },
  brand: { headerLogoPath: '', headerLogoAlt: 'Easylink', footerLogoPath: '', footerLogoAlt: 'Easylink' },
  social: { platforms: SOCIAL_PLATFORMS.map((id, i) => ({ id, active: false, url: '', order: i + 1 })) },
  defaultCta: { eyebrow: 'Következő lépés', title: 'Készen állsz könnyedebben vezetni a céged?', description: 'Kérj demót vagy próbáld ki ingyen a konfigurált Deploy felületen.', primaryLabel: 'Demót kérek', primaryUrl: DEFAULT_DEPLOY_URL, secondaryLabel: 'Próbáld ki ingyen', secondaryUrl: DEFAULT_DEPLOY_URL },
  searchVisibility: 'blocked',
};
export function validationError(message) { const e = new Error(message); e.code = 'VALIDATION_ERROR'; e.status = 400; return e; }
const limits = { companyName: 120, email: 254, phone: 40, postalCode: 20, city: 80, addressLine: 160, country: 80, label: 120, alt: 120, cta: 220 };
const contactKeys = Object.keys(DEFAULT_SITE_SETTINGS.contact);
function cleanText(v, key = 'label') { const s = String(v ?? '').trim(); if (s.length > (limits[key] || 220)) throw validationError('Túl hosszú mező.'); if (/[<>]/.test(s) || /javascript:/i.test(s) || /data:/i.test(s)) throw validationError('Hibás mezőérték.'); return s; }
function cleanContact(input = {}) { const c = input.contact || {}; const out = {}; for (const k of contactKeys) out[k] = cleanText(c[k] ?? DEFAULT_SITE_SETTINGS.contact[k], k); if (out.email && !/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(out.email)) throw validationError('Hibás email cím.'); if (out.phone && !/^[+()0-9 .\-/]{3,40}$/.test(out.phone)) throw validationError('Hibás telefonszám.'); return out; }
const cleanPath = (v) => String(v || '').trim();
export function safePublicUrl(v, { allowEmpty = true } = {}) { const s = String(v || '').trim(); if (!s) return allowEmpty ? '' : null; if (s.startsWith('//') || /[\u0000-\u001f\u007f"'<>]/.test(s)) return null; if (s.startsWith('/')) return s.startsWith('/assets/') || s.includes('..') ? null : s; try { const u = new URL(s); return ['http:', 'https:'].includes(u.protocol) ? s : null; } catch { return null; } }
function safeExternalUrl(v) { const s = String(v || '').trim(); if (!s) return ''; if (s.startsWith('//') || /[\u0000-\u001f\u007f"'<>]/.test(s)) return null; try { const u = new URL(s); return ['http:', 'https:'].includes(u.protocol) ? s : null; } catch { return null; } }
function cleanBrand(input = {}) { const b = input.brand || {}; return { headerLogoPath: cleanPath(b.headerLogoPath), headerLogoAlt: cleanText(b.headerLogoAlt || 'Easylink', 'alt') || 'Easylink', footerLogoPath: cleanPath(b.footerLogoPath), footerLogoAlt: cleanText(b.footerLogoAlt || 'Easylink', 'alt') || 'Easylink' }; }
function cleanSocial(input = {}) { const byId = new Map(((input.social?.platforms) || []).map((p) => [String(p.id), p])); return { platforms: SOCIAL_PLATFORMS.map((id, i) => { const p = byId.get(id) || {}; const active = !!p.active; const url = safeExternalUrl(p.url); if (active && !url) throw validationError(`Hibás ${id} social URL. Csak http/https profil URL adható meg.`); const order = Number(p.order ?? i + 1); return { id, active, url: url || '', order: Number.isFinite(order) ? Math.trunc(order) : i + 1 }; }) }; }
function docDefaults() { return structuredClone(DEFAULT_LEGAL_DOCUMENT_ITEMS); }
function cleanLegal(input = {}) { const l = input.legalDocuments || {}; const legacy = { terms: cleanPath(l.termsPdfPath), privacy: cleanPath(l.privacyPdfPath), cookie: cleanPath(l.cookiePdfPath) }; const byType = new Map((Array.isArray(l.items) ? l.items : []).map((d) => [String(d.type), d])); const items = docDefaults().map((def) => { const d = byType.get(def.type) || {}; const pdfPath = cleanPath(d.pdfPath || legacy[def.type] || ''); const label = cleanText(d.label ?? def.label, 'label') || def.label; const order = Number(d.order ?? def.order); return { type: def.type, label, pdfPath, active: d.active === undefined ? def.active : !!d.active, order: Number.isFinite(order) ? Math.trunc(order) : def.order }; }); const by = Object.fromEntries(items.map((d) => [d.type, d])); return { termsPdfPath: by.terms.active ? by.terms.pdfPath : '', privacyPdfPath: by.privacy.active ? by.privacy.pdfPath : '', cookiePdfPath: by.cookie.active ? by.cookie.pdfPath : '', items }; }
function cleanDefaultCta(input = {}) { const d = input.defaultCta || {}; const def = DEFAULT_SITE_SETTINGS.defaultCta; const primaryUrl = safePublicUrl(d.primaryUrl ?? def.primaryUrl); const secondaryUrl = safePublicUrl(d.secondaryUrl ?? def.secondaryUrl); if (primaryUrl === null || secondaryUrl === null) throw validationError('Hibás CTA URL. Csak biztonságos belső vagy http/https link adható meg.'); return { eyebrow: cleanText(d.eyebrow ?? def.eyebrow, 'cta'), title: cleanText(d.title ?? def.title, 'cta'), description: cleanText(d.description ?? def.description, 'cta'), primaryLabel: cleanText(d.primaryLabel ?? def.primaryLabel, 'cta'), primaryUrl: primaryUrl || '', secondaryLabel: cleanText(d.secondaryLabel ?? def.secondaryLabel, 'cta'), secondaryUrl: secondaryUrl || '' }; }
export function normalizeSiteSettings(input = {}) { const a = input.analytics || {}; const enabled = !!a.enabled; const provider = String(a.provider || 'none'); if (!['none','ga4'].includes(provider)) throw validationError('Hibás analytics szolgáltató.'); const ga4 = String(a.ga4MeasurementId || '').trim(); if (ga4 && !/^G-[A-Z0-9]{4,}$/.test(ga4)) throw validationError('Hibás GA4 Measurement ID.'); if (provider === 'ga4' && enabled && !ga4) throw validationError('GA4 Measurement ID szükséges.'); const consentMode = String(a.consentMode || 'basic'); if (consentMode !== 'basic') throw validationError('Csak basic consent mode engedélyezett.'); const ver = Number(a.consentConfigurationVersion ?? 1); if (!Number.isInteger(ver) || ver < 1) throw validationError('A consent verzió pozitív egész legyen.'); const searchVisibility = String(input.searchVisibility || 'blocked'); if (!['blocked','indexable'].includes(searchVisibility)) throw validationError('Hibás keresőmotoros láthatóság.'); return { analytics: { enabled, provider, ga4MeasurementId: ga4, consentMode, consentConfigurationVersion: ver }, legalDocuments: cleanLegal(input), contact: cleanContact(input), brand: cleanBrand(input), social: cleanSocial(input), defaultCta: cleanDefaultCta(input), searchVisibility }; }
export function parseSiteSettingsRows(rows = []) { const out = structuredClone(DEFAULT_SITE_SETTINGS); for (const r of rows) { let v = r.value; try { v = typeof v === 'string' ? JSON.parse(v) : v; } catch {} if (v && typeof v === 'object' && r.key in out) out[r.key] = { ...out[r.key], ...v }; if (r.key === 'searchVisibility') out.searchVisibility = typeof v === 'string' ? v : (v?.value || out.searchVisibility); } try { return normalizeSiteSettings(out); } catch { return structuredClone(DEFAULT_SITE_SETTINGS); } }
export function publicLegalDocuments(settings) { const docs = normalizeSiteSettings(settings).legalDocuments; const items = docs.items.filter((d) => d.active && d.pdfPath).sort((a, b) => a.order - b.order || LEGAL_DOCUMENT_TYPES.indexOf(a.type) - LEGAL_DOCUMENT_TYPES.indexOf(b.type)); const by = Object.fromEntries(items.map((d) => [d.type, d.pdfPath])); return { termsPdfPath: by.terms || '', privacyPdfPath: by.privacy || '', cookiePdfPath: by.cookie || '', items }; }
export function publicContact(settings) { return normalizeSiteSettings(settings).contact; }
export function publicBrand(settings) { const b = normalizeSiteSettings(settings).brand; return { headerLogoPath: b.headerLogoPath || LEGACY_LOGO_PATH, headerLogoAlt: b.headerLogoPath ? b.headerLogoAlt : 'Easylink', footerLogoPath: b.footerLogoPath || LEGACY_LOGO_PATH, footerLogoAlt: b.footerLogoPath ? b.footerLogoAlt : 'Easylink' }; }
export function publicSocial(settings) { return normalizeSiteSettings(settings).social.platforms.filter((p) => p.active && safeExternalUrl(p.url)).sort((a, b) => a.order - b.order || SOCIAL_PLATFORMS.indexOf(a.id) - SOCIAL_PLATFORMS.indexOf(b.id)); }
