export const DEFAULT_SITE_SETTINGS={analytics:{enabled:false,provider:'none',ga4MeasurementId:'',consentMode:'basic',consentConfigurationVersion:1},legalDocuments:{termsPdfPath:'',privacyPdfPath:'',cookiePdfPath:''},contact:{companyName:'',email:'hello@easylink.hu',phone:'',postalCode:'',city:'',addressLine:'',country:'Magyarország'}};
export function validationError(message){const e=new Error(message);e.code='VALIDATION_ERROR';e.status=400;return e;}
const limits={companyName:120,email:254,phone:40,postalCode:20,city:80,addressLine:160,country:80};
const contactKeys=Object.keys(DEFAULT_SITE_SETTINGS.contact);
function cleanText(v,key){const s=String(v||'').trim();if(s.length>limits[key])throw validationError('Túl hosszú kapcsolati adat.');if(/[<>]/.test(s)||/javascript:/i.test(s)||/data:/i.test(s))throw validationError('Hibás kapcsolati adat.');return s;}
function cleanContact(input={}){const c=input.contact||{};const out={};for(const k of contactKeys)out[k]=cleanText(c[k]??DEFAULT_SITE_SETTINGS.contact[k],k);if(out.email&&!/^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$/.test(out.email))throw validationError('Hibás email cím.');if(out.phone&&!/^[+()0-9 .\-/]{3,40}$/.test(out.phone))throw validationError('Hibás telefonszám.');return out;}
export function normalizeSiteSettings(input={}){const a=input.analytics||{},l=input.legalDocuments||{};const enabled=!!a.enabled;const provider=String(a.provider||'none');if(!['none','ga4'].includes(provider))throw validationError('Hibás analytics szolgáltató.');const ga4=String(a.ga4MeasurementId||'').trim();if(ga4&&!/^G-[A-Z0-9]{4,}$/.test(ga4))throw validationError('Hibás GA4 Measurement ID.');if(provider==='ga4'&&enabled&&!ga4)throw validationError('GA4 Measurement ID szükséges.');const consentMode=String(a.consentMode||'basic');if(consentMode!=='basic')throw validationError('Csak basic consent mode engedélyezett.');const ver=Number(a.consentConfigurationVersion??1);if(!Number.isInteger(ver)||ver<1)throw validationError('A consent verzió pozitív egész legyen.');const cleanPath=(v)=>String(v||'').trim();return {analytics:{enabled,provider,ga4MeasurementId:ga4,consentMode,consentConfigurationVersion:ver},legalDocuments:{termsPdfPath:cleanPath(l.termsPdfPath),privacyPdfPath:cleanPath(l.privacyPdfPath),cookiePdfPath:cleanPath(l.cookiePdfPath)},contact:cleanContact(input)};}
export function parseSiteSettingsRows(rows=[]){const out=structuredClone(DEFAULT_SITE_SETTINGS);for(const r of rows){let v=r.value;try{v=typeof v==='string'?JSON.parse(v):v;}catch{} if(r.key==='analytics'&&v&&typeof v==='object')out.analytics={...out.analytics,...v}; if(r.key==='legalDocuments'&&v&&typeof v==='object')out.legalDocuments={...out.legalDocuments,...v}; if(r.key==='contact'&&v&&typeof v==='object')out.contact={...out.contact,...v};}try{return normalizeSiteSettings(out);}catch{return structuredClone(DEFAULT_SITE_SETTINGS);}}
export function publicLegalDocuments(settings){const docs=settings?.legalDocuments||{};return {termsPdfPath:docs.termsPdfPath||'',privacyPdfPath:docs.privacyPdfPath||'',cookiePdfPath:docs.cookiePdfPath||''};}
export function publicContact(settings){return normalizeSiteSettings(settings).contact;}
