export type SearchVisibility = 'blocked' | 'indexable';
export type AnalyticsSettings = { enabled: boolean; provider: 'none' | 'ga4'; ga4MeasurementId: string; consentMode: 'basic'; consentConfigurationVersion: number };
export type ContactSettings = { companyName: string; email: string; phone: string; postalCode: string; city: string; addressLine: string; country: string };
export type BrandSettings = { headerLogoPath: string; headerLogoAlt: string; footerLogoPath: string; footerLogoAlt: string };
export type SocialPlatformId = 'facebook' | 'instagram' | 'tiktok' | 'youtube' | 'linkedin';
export type SocialPlatformSettings = { id: SocialPlatformId; active: boolean; url: string; order: number };
export type SocialSettings = { platforms: SocialPlatformSettings[] };
export type LegalDocumentType = 'terms' | 'privacy' | 'cookie';
export type LegalDocumentItem = { type: LegalDocumentType; label: string; pdfPath: string; active: boolean; order: number };
export type LegalDocumentsSettings = { termsPdfPath: string; privacyPdfPath: string; cookiePdfPath: string; items: LegalDocumentItem[] };
export type DefaultCtaSettings = { eyebrow: string; title: string; description: string; primaryLabel: string; primaryUrl: string; secondaryLabel: string; secondaryUrl: string };
export type SiteSettings = { analytics: AnalyticsSettings; legalDocuments: LegalDocumentsSettings; contact: ContactSettings; brand: BrandSettings; social: SocialSettings; defaultCta: DefaultCtaSettings; searchVisibility: SearchVisibility };
export const LEGACY_LOGO_PATH: '/assets/brand/easylink-logo-horizontal.png';
export const DEFAULT_DEPLOY_URL: string;
export const SOCIAL_PLATFORMS: SocialPlatformId[];
export const LEGAL_DOCUMENT_TYPES: LegalDocumentType[];
export const DEFAULT_LEGAL_DOCUMENT_ITEMS: LegalDocumentItem[];
export const DEFAULT_SITE_SETTINGS: SiteSettings;
export function normalizeSiteSettings(input?: unknown): SiteSettings;
export function parseSiteSettingsRows(rows?: Array<{ key: string; value: unknown }>): SiteSettings;
export function publicLegalDocuments(settings: SiteSettings): LegalDocumentsSettings;
export function publicContact(settings: SiteSettings): ContactSettings;
export function publicBrand(settings: SiteSettings): BrandSettings;
export function publicSocial(settings: SiteSettings): SocialPlatformSettings[];
export function safePublicUrl(value: unknown, options?: { allowEmpty?: boolean }): string | null;
