import crypto from 'node:crypto';
import { hashPassword } from '../db/client.mjs';
import { adminScopes, scopeActions, defaultNewUserPermissionMatrix, fullAdminPermissionMatrix, normalizePermissions, permissionRowsForInsert } from './permissions.mjs';
const actionKeys = { save:'canSave', archive:'canArchive', delete:'canDelete', republish:'canRepublish', restore:'canRestore' };
export function userError(status, code, message) { const e = new Error(message); e.status = status; e.code = code; return e; }
export const normalizeEmail = (v) => String(v || '').trim().toLowerCase();
export function publicUser(row, permissions) { return { id: row.id, email: row.email, display_name: row.display_name, status: row.status, created_at: row.created_at, updated_at: row.updated_at, last_login_at: row.last_login_at, ...(permissions ? { permissions } : {}) }; }
export function normalizePermissionMatrix(input = defaultNewUserPermissionMatrix) { const rows = []; const matrix = {}; for (const scope of adminScopes) { const src = input?.[scope]; if (!src) continue; const row = {}; for (const a of scopeActions[scope]) { if (scope === 'media' && a === 'delete') continue; row[actionKeys[a]] = Boolean(src[actionKeys[a]]); } matrix[scope] = { canSave:false, canArchive:false, canDelete:false, canRepublish:false, canRestore:false, ...row }; } return normalizePermissions(Object.entries(matrix).map(([scope_code,p]) => ({ scope_code, can_save:p.canSave, can_archive:p.canArchive, can_delete:p.canDelete, can_republish:p.canRepublish, can_restore:p.canRestore }))); }
export function validateUserPayload(payload = {}, { create = false } = {}) { const display_name = String(payload.display_name ?? payload.displayName ?? '').trim(); const email = normalizeEmail(payload.email); if (!display_name) throw userError(400, 'INVALID_USER', 'A megjelenített név kötelező.'); if (!/^\S+@\S+\.\S+$/.test(email)) throw userError(400, 'INVALID_USER', 'Érvényes e-mail-cím szükséges.'); const status = String(payload.status || 'active'); if (!['active','disabled'].includes(status)) throw userError(400, 'INVALID_USER_STATUS', 'Hibás felhasználói státusz.'); return { display_name, email, status: create ? 'active' : status, permissions: normalizePermissionMatrix(payload.permissions || defaultNewUserPermissionMatrix) }; }
export function classifyUserMutation(current, payload = {}) { const status = payload.status || current.status; const dataChanged = ['display_name','displayName','email','permissions'].some((k)=>Object.prototype.hasOwnProperty.call(payload,k)); return { needsSave: dataChanged || (current.status === 'disabled' && status === 'active'), needsArchive: current.status === 'active' && status === 'disabled' }; }
export function isFullAdminMatrix(matrix = {}) { return adminScopes.every((scope) => matrix?.[scope] && scopeActions[scope].filter((a) => !(scope === 'media' && a === 'delete')).every((a) => matrix[scope][actionKeys[a]] === true)); }
export function unknownCredentialHash() { return hashPassword(crypto.randomBytes(32).toString('base64url')); }
export function rowsFromMatrix(matrix) { return permissionRowsForInsert(normalizePermissionMatrix(matrix)); }
